/** @type {import('tailwindcss').Config} */
import defaultTheme from 'tailwindcss/defaultTheme'

export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        light: {
          primary: '#36693D',
          surfaceTint: '#36693D',
          onPrimary: '#FFFFFF',
          primaryContainer: '#B8F1B9',
          onPrimaryContainer: '#002108',
          secondary: '#516350',
          onSecondary: '#FFFFFF',
          secondaryContainer: '#D4E8D0',
          onSecondaryContainer: '#0F1F11',
          tertiary: '#39656C',
          onTertiary: '#FFFFFF',
          tertiaryContainer: '#BDEAF3',
          onTertiaryContainer: '#001F24',
          error: '#BA1A1A',
          onError: '#FFFFFF',
          errorContainer: '#FFDAD6',
          onErrorContainer: '#410002',
          background: '#F7FBF2',
          onBackground: '#181D18',
          surface: '#F7FBF2',
          onSurface: '#181D18',
          surfaceVariant: '#DEE5D9',
          onSurfaceVariant: '#424940',
          outline: '#727970',
          outlineVariant: '#C1C9BE',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#2D322C',
          inverseOnSurface: '#EEF2E9',
          inversePrimary: '#9DD49E',
          primaryFixed: '#B8F1B9',
          onPrimaryFixed: '#002108',
          primaryFixedDim: '#9DD49E',
          onPrimaryFixedVariant: '#1E5128',
          secondaryFixed: '#D4E8D0',
          onSecondaryFixed: '#0F1F11',
          secondaryFixedDim: '#B8CCB5',
          onSecondaryFixedVariant: '#3A4B3A',
          tertiaryFixed: '#BDEAF3',
          onTertiaryFixed: '#001F24',
          tertiaryFixedDim: '#A1CED6',
          onTertiaryFixedVariant: '#1F4D54',
          surfaceDim: '#D7DBD3',
          surfaceBright: '#F7FBF2',
          surfaceContainerLowest: '#FFFFFF',
          surfaceContainerLow: '#F1F5EC',
          surfaceContainer: '#EBEFE7',
          surfaceContainerHigh: '#E5E9E1',
          surfaceContainerHighest: '#E0E4DB'
        },
        dark: {
          primary: '#9DD49E',
          surfaceTint: '#9DD49E',
          onPrimary: '#013913',
          primaryContainer: '#1E5128',
          onPrimaryContainer: '#B8F1B9',
          secondary: '#B8CCB5',
          onSecondary: '#243424',
          secondaryContainer: '#3A4B3A',
          onSecondaryContainer: '#D4E8D0',
          tertiary: '#A1CED6',
          onTertiary: '#00363D',
          tertiaryContainer: '#1F4D54',
          onTertiaryContainer: '#BDEAF3',
          error: '#FFB4AB',
          onError: '#690005',
          errorContainer: '#93000A',
          onErrorContainer: '#FFDAD6',
          background: '#101510',
          onBackground: '#E0E4DB',
          surface: '#101510',
          onSurface: '#E0E4DB',
          surfaceVariant: '#424940',
          onSurfaceVariant: '#C1C9BE',
          outline: '#8C9389',
          outlineVariant: '#424940',
          shadow: '#000000',
          scrim: '#000000',
          inverseSurface: '#E0E4DB',
          inverseOnSurface: '#2D322C',
          inversePrimary: '#36693D',
          primaryFixed: '#B8F1B9',
          onPrimaryFixed: '#002108',
          primaryFixedDim: '#9DD49E',
          onPrimaryFixedVariant: '#1E5128',
          secondaryFixed: '#D4E8D0',
          onSecondaryFixed: '#0F1F11',
          secondaryFixedDim: '#B8CCB5',
          onSecondaryFixedVariant: '#3A4B3A',
          tertiaryFixed: '#BDEAF3',
          onTertiaryFixed: '#001F24',
          tertiaryFixedDim: '#A1CED6',
          onTertiaryFixedVariant: '#1F4D54',
          surfaceDim: '#101510',
          surfaceBright: '#363A35',
          surfaceContainerLowest: '#0B0F0B',
          surfaceContainerLow: '#181D18',
          surfaceContainer: '#1C211C',
          surfaceContainerHigh: '#272B26',
          surfaceContainerHighest: '#313630'
        }
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans]
      }
    }
  },
  plugins: []
}
